main: com.gmail.iledrome.MotherPlugin
name: Mother
author: iledrome
description: Core Plugin for The Ravens Nest SMP Server!
version: 1.0

commands:
  homes:
    description: Homes Command!
  pin:
    description: Pin Command!